name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GO_VERSION: 1.23.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Run linting
        run: make lint
      
      - name: Run unit tests
        run: make test

      - name: Build binary
        run: make binary

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        run: make image

  publish:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare buildx environment
        run: make prepare-buildx

      - name: Build and Push container images
        run: make build-push-image
